server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://badhon8804:badhon321@cluster1.kmjg0hs.mongodb.net/blood_donation?appName=Cluster1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:Ymxvb2Rkb25hdGlvbnNlY3JldGtleXRoYXRpc2xvbmdlbm91Z2hmb3JoczI1Ng==}
  expiration: 86400000

app:
  cors:
    allowed-origins: http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174,http://localhost:5175,http://127.0.0.1:5175
